### ISSUE TITLE
Some of exif types are not supported

### ISSUE THREAD

**Issue by HFN** [hMatoba/Piexif#14]
Due to [this documentation](http://www.media.mit.edu/pia/Research/deepview/exif.html), There are 12 types of data formats for exif files. Unfortunately some of these formats is not supported in this package (e.g. value 8), Which leads to a ValueError Exception.
Can you please fix it so it can be also possible to use these kinds of formats?

**Comment by HFN** [comment]
I'm still waiting for some answers. There are still no support for signed byte, signed short, float and double. Could you please also support these formats or at least show me a way to do it myself?

**Comment by hMatoba** [comment]
They aren't described in exif official document. If I find them in more reliable document, I'll write code to support them.

**Comment by Alex131089** [comment]
http://www.randelshofer.ch/multishow/javadoc/ch/randelshofer/media/tiff/IFDDataType.html#SSHORT lead me to http://www.alternatiff.com/resources/TIFFPM6.pdf page 7 you find the type 8.
Also, https://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf page 16.
ExifTool use those types : https://sourceforge.net/p/exiftool/code/ci/master/tree/lib/Image/ExifTool/Exif.pm#l86

Not related but I found those too and they can be useful : 
http://www.exiv2.org/metadata.html
http://www.sno.phy.queensu.ca/~phil/exiftool/standards.html#ref1

**Comment by hMatoba** [comment]
Thanks.
I want official documents. They aren't any lib's documents.
I'll check adobe's.

**Comment by hMatoba** [comment]
Resolved.
