### ISSUE TITLE
insert() raises ValueError with non-jpg files

### ISSUE THREAD

**Issue by ZacDiggum** [hMatoba/Piexif#15]
Hi,

I'm trying to write exif data to tif images. As I already noticed in the docs piexif seems to support jpg only. As a result I get a ValueError from _insert.py (line 26 / 27). Would it be possible to add tif support to piexif? If not, do you know about an alternative for writing exif to tif?

Thanks...

**Comment by hMatoba** [comment]
Tiff tag is not exif. It is tiff tag.
Piexif won't support to write tiff tag.

**Comment by ZacDiggum** [comment]
Okay, thanks for the quick answer.
