### ISSUE TITLE
GPS removal causes Bad IFD1 directory error

### ISSUE THREAD

**Issue by bnice5000** [hMatoba/Piexif#16]
I am working on creating a tool to pull the exif data from an image and remove the GPS data. I use pillow to read in the file. I then use the following function to extract the exif and remove the GPS data.

```python
def manipulate_exif(img, remove_gps):

    try:
        import piexif
    except ImportError:
        raise

    try:
        exif = piexif.load(img.info['exif'])
        
        if remove_gps:
            exif.get('GPS', None).clear()
            print '{}'.format(pprint.pformat(exif))

    except Exception:
        exif = {}

    return piexif.dump(exif)
```

When I use it with the `remove_gps` flag set to `False` the function works as expected. However when I set `remove_gps` to `True`, I get weird field overflow issues in some of the fields and I get `Bad IFD1 directory` error in the exif file where the GPS data existed before.

I am not sure if this is a bug in Piexif or I am using Piexif incorrectly. Any help is most appreciated!

**Comment by hMatoba** [comment]
Can I have your jpeg file? You can upload by "Drug and drop".
I'll try it this weekend.

**Comment by bnice5000** [comment]
I have included the files below. I do not know if github manipulates the files on upload. I can send you a direct upload if it will help. 

Also, here is some complete sample code.

```Python
from PIL import Image

def manipulate_exif(img, remove_gps):

    try:
        import piexif
    except ImportError:
        raise

    try:
        exif = piexif.load(img.info['exif'])

        if remove_gps:
            exif.get('GPS', None).clear()
            print '{}'.format(pprint.pformat(exif))

    except Exception:
        exif = {}

    return piexif.dump(exif)

from PIL import Image
img = Image.open('./IMG_0264.jpg')

# Creates Issue
exif_copy_bad = manipulate_exif(img, True)

# No issue
exif_copy_good = manipulate_exif(img, False)

img.save('./Test_Bad.jpg', 'JPEG', exif=exif_copy_bad)
img.save('./Test_Good.jpg', 'JPEG', exif=exif_copy_good)
```

This is the original image that I am manipulating. ![img_2223.jpg](https://cloud.githubusercontent.com/assets/100688/17021036/248f46de-4f13-11e6-873e-c42e0ff9f358.jpg)

This is the result with the GPS removed. ![test_bad.jpg](https://cloud.githubusercontent.com/assets/100688/17021038/24a19654-4f13-11e6-9728-34fe1bcb9d18.jpg)

This is the result with the GPS intact. ![test_good.jpg](https://cloud.githubusercontent.com/assets/100688/17021037/249b044c-4f13-11e6-8009-7eef9d5bc1fe.jpg)

This is the Exif from test_bad.jpg derived using exiftool. [Exif_Bad.txt](https://github.com/hMatoba/Piexif/files/375788/Exif_Bad.txt)

This is the Exif from test_good.jpg derived using exiftool. [Exif_Good.txt](https://github.com/hMatoba/Piexif/files/375787/Exif_Good.txt)

This is a diff of the two derived exif files.  [exif.diff.txt](https://github.com/hMatoba/Piexif/files/375810/exif.diff.txt)

Let me know if there is anything else I can provide or try.

**Comment by hMatoba** [comment]
Hmm... No error occured.

Python: 3.5
Piexif: Latest on this repos

    from PIL import Image
    import piexif
    
    def manipulate_exif(img, remove_gps):
        exif = piexif.load(img.info['exif'])
    
        if remove_gps:
            exif.get('GPS', None).clear()
    
        print(exif["GPS"])
    
        return piexif.dump(exif)
    
    img = Image.open('./IMG_0264.jpg')
    exif_copy_bad = manipulate_exif(img, True)

If You still get bug, try below to remove a GPS IFD.
exif.pop("GPS")

**Comment by bnice5000** [comment]
I have tried to emulate your environment and I am still getting the same error. It appear to be an binary overflow error in the dump process.

I am using Mac OS X version 10.11.6 (15G31). I have created a python 3.5.2 environment with the following compilation flags.

[pythonconfig.txt](https://github.com/hMatoba/Piexif/files/379533/pythonconfig.txt)

I have switched to the repo version of piexif. My pip library is as follows:
[requirements.txt](https://github.com/hMatoba/Piexif/files/379534/requirements.txt)

I have altered the script to use pop so it now looks like this:

```python
from PIL import Image

def manipulate_exif(img, remove_gps):

    try:
        import piexif
    except ImportError:
        raise

    try:
        exif = piexif.load(img.info['exif'])

        if remove_gps:
            exif.pop('GPS')

    except Exception:
        exif = {}

    return piexif.dump(exif)

from PIL import Image
img = Image.open('./IMG_2223.jpg')

# Creates Issue
exif_copy_bad = manipulate_exif(img, True)

# No issue
exif_copy_good = manipulate_exif(img, False)

img.save('./Test_Bad.jpg', 'JPEG', exif=exif_copy_bad)
img.save('./Test_Good.jpg', 'JPEG', exif=exif_copy_good)
```

I then get the following exifs:

[Good_exif.txt](https://github.com/hMatoba/Piexif/files/379537/Good_exif.txt)
[Bad_exif.txt](https://github.com/hMatoba/Piexif/files/379538/Bad_exif.txt)
[exif.diff.txt](https://github.com/hMatoba/Piexif/files/379539/exif.diff.txt)

The reason I think it is a binary overflow issue on the dump process is because the information looks fine when I only look at it as a dictionary but when I dump it and save it back to the image it starts flowing into other fields. If you look at the good_exif versus bad_exif you see that when using dump it turns:

```
Make                            : Apple
Camera Model Name               : iPhone 6 Plus
```

into

```
Make                            :  6 Plu
Camera Model Name               : s
```

**Comment by hMatoba** [comment]
Paste here whole of python error message.

**Comment by bnice5000** [comment]
There is no error message in python. The error message is in the exif itself.

**Comment by hMatoba** [comment]
in process.

**Comment by bnice5000** [comment]
Very cool! Thank you.

**Comment by hMatoba** [comment]
Fixed code was committed.
Next, enough test, upload PyPI and edit document.

**Comment by hMatoba** [comment]
Finish.

**Comment by bnice5000** [comment]
Thank you, now works as expected.
