### ISSUE TITLE
no tar-ball or zip on pypi

### ISSUE THREAD

**Issue by arunpersaud** [hMatoba/Piexif#18]
Hi

1.0.5 doesn't seem to have a source release on pypi. Would be great to add it over there, especially for linux distribution who build their packages from these (I'm trying to package the latest version for opensuse).
(the changelog also doesn't seem to have 1.0.5 information)

thanks

Arun

**Comment by hMatoba** [comment]
Thank you.
https://pypi.python.org/pypi/piexif
http://piexif.readthedocs.io/en/latest/changes.html
