### ISSUE TITLE
Issue with ProfileCopyright Field 

### ISSUE THREAD

**Issue by bnice5000** [hMatoba/Piexif#19]
When I run the following code there is no python issue however, the exif that is generated has a weird occurrence. I believe that [`ProfileCopyright`](http://www.exiv2.org/tags.html) in the exif is a UTF-8 byte array. When I encode the field, I just get back the integer values of the text I have inputed. I am sure that I am just misunderstanding how to encode this information. Any help is most appreciated. Sample code below.

```python
import piexif
from PIL import Image


def manipulate_exif(img, remove_gps):

    author = 'Brian Levin'
    license = '{} 2016, All Rights Reserved'

    exif = piexif.load(img.info['exif'])
    exif['0th'][piexif.ImageIFD.Artist] = author
    exif['0th'][piexif.ImageIFD.XPAuthor] = bytearray(author, 'utf-16')

    # Line with issue
    exif['0th'][piexif.ImageIFD.ProfileCopyright] = bytearray(license.format(author), 'utf-8')
    # End Line with issue   
    
    exif['0th'][piexif.ImageIFD.Copyright] = license
    
    return piexif.dump(exif)


img = Image.open('./IMG_2223.jpg')
exif_copy = manipulate_exif(img, False)
img.save('./Test.jpg', 'JPEG', exif=exif_copy)
```

This produces the following exif statement for `ProfileCopyright`:

```bash
ProfileCopyright: 123 125 32 50 48 49 54 44 32 65 108 108 32 82 105 103 104 116 115 32 82 101 115 101 114 118 101 100
```

**Comment by hMatoba** [comment]
It can't use UTF-8 string for exif value, so encode and decode between UTF-8 string and byte array  by yourself.

**Comment by bnice5000** [comment]
I believe my current code does this and the result is not human readable. Can you give me a code example that would put a human readable value in `profilecopyright`?

**Comment by hMatoba** [comment]
Hmm... like below?

    "".join([chr(s) for s in profilecopyright])

Just the tip.

**Comment by bnice5000** [comment]
I mean in the actual exif. I can use exiftool to set a human readable value in `ProfileCopyright`. Can I use piexif to set this to a human readable value in the exif? Or are you saying that it will always be a block of integers if I use piexif?

**Comment by hMatoba** [comment]
Type of ProfileCopyright is "Byte". It's as tuple of byte in piexif.

**Comment by bnice5000** [comment]
Right, I get that. When I write `XPAuthor` as a utf-16 per the standard, I use to following code and it works as expected. It converts the string author into an array of bytes using the utf-16 character set.

`exif['0th'][piexif.ImageIFD.XPAuthor] = bytearray(author, 'utf-16')`

However, when I want to write `ProfileCopyright` as a utf-8 per the standard, I use the following code and it produces abnormal results in the exif. It converts the byte array of utf-8 into a string literal of integers.

`exif['0th'][piexif.ImageIFD.ProfileCopyright] = bytearray(license.format(author), 'utf-8')`

The piexif library is not behaving as expected. It is producing an incorrect result.

**Comment by hMatoba** [comment]
Can you paste here input and result both UTF8 and UTF16?

**Comment by bnice5000** [comment]
I am running Python 3.5.2 but I have also tested the above script in Python 2.7.12.

I have wrapped the bytearray in a tuple per your instruction and it made no difference. This is the bytearray output from the script that is fed into the exif.

```
utf8: (66, 114, 105, 97, 110, 32, 76, 101, 118, 105, 110, 32, 50, 48, 49, 54, 44, 32, 65, 108, 108, 32, 82, 105, 103, 104, 116, 115, 32, 82, 101, 115, 101, 114, 118, 101, 100)

utf16: (255, 254, 66, 0, 114, 0, 105, 0, 97, 0, 110, 0, 32, 0, 76, 0, 101, 0, 118, 0, 105, 0, 110, 0)
```

The utf16 works as expected. The utf8 does not work.

Here is the script to generate the about output.

```python
import piexif
from PIL import Image


def manipulate_exif(img, remove_gps):

    author = 'Brian Levin'
    license = '{} 2016, All Rights Reserved'
    utf8_bytearray = tuple(bytearray(license.format(author), 'utf-8'))
    utf16_bytearray = tuple(bytearray(author, 'utf-16'))

    print('utf8: {}'.format(utf8_bytearray))
    print('utf16: {}'.format(utf16_bytearray))

    exif = piexif.load(img.info['exif'])
    exif['0th'][piexif.ImageIFD.Artist] = author
    exif['0th'][piexif.ImageIFD.XPAuthor] = utf16_bytearray

    exif['0th'][piexif.ImageIFD.ProfileCopyright] = utf8_bytearray
    exif['0th'][piexif.ImageIFD.Copyright] = license.format(author)

    return piexif.dump(exif)


img = Image.open('./IMG_2223.jpg')
exif_copy = manipulate_exif(img, False)
img.save('./Test.jpg', 'JPEG', exif=exif_copy)
```

Here is the image that I ran the script on.

![img_2223](https://cloud.githubusercontent.com/assets/100688/17350052/20daab90-58f1-11e6-8bbc-67ef3b82e8e5.jpg)

Here is the result of the script:

![test](https://cloud.githubusercontent.com/assets/100688/17350071/4de0216a-58f1-11e6-8d73-83107113c9ff.jpg)
[img_2223.exif.txt](https://github.com/hMatoba/Piexif/files/398427/img_2223.exif.txt)

**Comment by hMatoba** [comment]
Piexif returns ProfileCopyright value as "(int, int...)". Isn't it a exiftool's matter?

    import piexif
    from PIL import Image
    
    author = 'Brian Levin'
    license = '{} 2016, All Rights Reserved'
    s = bytearray(license.format(author), 'utf-8')
    e = {"0th":{piexif.ImageIFD.ProfileCopyright:s}}
    exif_bytes = piexif.dump(e)
    
    i = Image.open("a.jpg")
    i.save('b.jpg', exif=exif_bytes)
    
    exif1 = piexif.load("b.jpg")
    print(exif1["0th"][piexif.ImageIFD.ProfileCopyright])
    "".join([chr(s) for s in exif1["0th"][piexif.ImageIFD.ProfileCopyright]])
    
    i2 = Image.open("b.jpg")
    exif2 =  i2._getexif()
    print(exif2[piexif.ImageIFD.ProfileCopyright])

**Comment by bnice5000** [comment]
No, I get the same result (a list of integers) with iPhoto, Photos, Aperture, Lightroom, Photoshop, http://regex.info/exif.cgi, and every other program that I have that reads exif data. However, if I use exiftool to set that value they all return a normal (human readable text) result and not a string of integers. 

So either they are all wrong in how they are reading and writing the exif or there is something wrong with the way piexif is reading and writing the exif.

**Comment by bnice5000** [comment]
I have filed a bug report over at Exiftool to see if we can determine in which code base the issue exists.

http://u88.n24.queensu.ca/exiftool/forum/index.php/topic,7424.0.html

**Comment by hMatoba** [comment]
Have you compared list of integers value between correct exif jpg and wrong exif jpg in piexif?

**Comment by bnice5000** [comment]
Yes, the text is correct when it is back converted from integers to a string. However, it should be text not integers in the exif and it should not require back converting to text. 

The crux of the issue is when I use exiftool to modify that text it is text and not a string of integers. When I use Piexif it is a string of integers. Either Piexif isn't writing the data correctly to the exif or exiftool is not reading it correctly.

You stated the issue was with Exiftool. Posted an issue ticket over there to make sure that is not the case.

My guess is the issue is with Piexif because Exiftool can also write to the exif and it produces the correct result.

**Comment by hMatoba** [comment]
Upload correct exif jpg here.

**Comment by hMatoba** [comment]
I guess that if type is UTF8, the value should be append some flag.

**Comment by bnice5000** [comment]
Here is a correct exif for the ProfileCopyright field. 

![test_correct](https://cloud.githubusercontent.com/assets/100688/17364388/ef5b9e28-594d-11e6-92ac-30f20fcdb723.jpg)

Here is a dump of the exif.

[Test_Correct.jpg.exif.txt](https://github.com/hMatoba/Piexif/files/399352/Test_Correct.jpg.exif.txt)

**Comment by hMatoba** [comment]
Conclusion is that exiftool and piexif have no bug. There is a specification difference between two lib.
Exiftool supports "ProfileCopyright" as string(http://search.cpan.org/~exiftool/Image-ExifTool-10.20/lib/Image/ExifTool/TagNames.pod).
In piexif, it is as tuple of byte. Piexif references Exiv2 tags(http://www.exiv2.org/tags.html).

**Comment by bnice5000** [comment]
You are correct. It is fixed in the next version of exiftool to match your specification.

See http://u88.n24.queensu.ca/exiftool/forum/index.php/topic,7424.0.html

**Comment by hMatoba** [comment]
To understand specification is good way to understand matter.
