### ISSUE TITLE
Files missing from the zip file and required for testing

### ISSUE THREAD

**Issue by jose-matos** [hMatoba/Piexif#22]
While packaging this file to Fedora I noticed that there are two files that required to test the package and that are missing from the zip file:

tests/s_test.py
tests/images/01.tif

Could you, please, add them to the source package?

**Comment by hMatoba** [comment]
I don't know the correct command.

    python setup.py sdist --formats=zip

**Comment by jose-matos** [comment]
Without testing I would expect to enough to change MANIFEST.in line to include

recursive-include tests *.jpg *.py *.tif

**Comment by hMatoba** [comment]
Thank you!

**Comment by jose-matos** [comment]
Thank you for making a new release with the files on. Now the package passes the tests. :-)
