### ISSUE TITLE
Files with no or other suffix are false negatives

### ISSUE THREAD

**Issue by FelixHaller** [hMatoba/Piexif#24]
When performing `piexif.load() `on a valid JPEG-File named **testpic.docx** or **testpic** I get a _ValueError_ saying 
> Given file is neither JPEG nor TIFF

It's a lie!

Piexif should not consider the suffix to check if the file is valid. I personally use the [imghdr](https://docs.python.org/3/library/imghdr.html) python module to check if a file is valid and would appreciate a _check=False_ parameter for `piexif.load()` to skip unnecessary checks.

Thanks in advance
Felix

**Comment by hMatoba** [comment]
No file? No code?

**Comment by hMatoba** [comment]
Piexif checkds SOI.

**Comment by FelixHaller** [comment]
You can use any jpg file. I attached one anyway. I think the check for SOI doesn't work, because the attached image starts with `FF D8` and is reported as no JPEG.
[Android.Statue.Garden.jpg.docx](https://github.com/hMatoba/Piexif/files/484559/Android.Statue.Garden.jpg.docx)

**Comment by FelixHaller** [comment]
for code see #25

**Comment by hMatoba** [comment]
Thank you. But I want to looking for a way not to add argument. Give me a while.

**Comment by hMatoba** [comment]
Done.
