### ISSUE TITLE
Webp

### ISSUE THREAD

**Issue by alexislg2** [hMatoba/Piexif#26]
Hello,
thanks for your plugin. How can I use your package with webp pictures?

**Comment by hMatoba** [comment]
Not support.

**Comment by hMatoba** [comment]
WebP should be supported.

https://github.com/hMatoba/Piexif/projects/4

**Comment by hMatoba** [comment]
Piexif will support for WebP in a few weeks.
https://github.com/hMatoba/Piexif/projects/4
