### ISSUE TITLE
Add support for custom XMP tags like ProjectionType

### ISSUE THREAD

**Issue by jo-chemla** [hMatoba/Piexif#28]
Cannot put a custom XMP tag like ProjectionType, which can be useful for 360 images. Adding it in the library could be a good addition.

**Comment by hMatoba** [comment]
XMP? Not Exif?

**Comment by hMatoba** [comment]
I want documents, and examples.

**Comment by jo-chemla** [comment]
Yes, do you plan to add support for XMP tags with your library? For example, for spherical images, it can be interesting to embed the ProjectionType tag: 
https://developers.google.com/streetview/spherical-metadata

**Comment by hMatoba** [comment]
No. Just for exif.
