### ISSUE TITLE
Exposing field name

### ISSUE THREAD

**Issue by sshevlyagin** [hMatoba/Piexif#29]
Great library! Just used it to do some annoying exif tag updates.

Have you considered exposing field names in the exif_dictionary returned by the load function? For example, it would be great to know 36867 is DateTimeOriginal without having to reference http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf

**Comment by hMatoba** [comment]
load(filename, True)

https://github.com/hMatoba/Piexif/commit/9fee596ff69267ddef9043bcec19e811630dd71e

Thank you for your suggestion : )

**Comment by sshevlyagin** [comment]
Awesome, thanks!
