### ISSUE TITLE
Buggy example - yet: this is amazing!

### ISSUE THREAD

**Issue by SimonSteinberger** [hMatoba/Piexif#3]
Hi, your example doesn't work when using tuples:

gps_ifd = {
    pyxif.GPSIFD.GPSVersionID: 1,
    pyxif.GPSIFD.GPSDateStamp: "1999:99:99 99:99:99",
}

Traceback:

File "pyxif\_load_and_dump.py", line 373, in dict_to_bytes
    value_str = raw_value + b"\x00" * (4 - length)
TypeError: can only concatenate tuple (not "str") to tuple

It works when using pyxif.GPSIFD.GPSVersionID: "1" -> string instead of int as value.

Apart from that, your lib looks very promising! If this works, we'll make use of it on Pixabay.com and we'll certainly write about it on our blog :-) Keep up the great work!

It clean and simple and doesn't require unreliable third party libs, such as pyexiv2 ...

**Comment by SimonSteinberger** [comment]
I've narrowed the issue down a bit. I run into trouble when using Short and Byte values.

E.g. assigning a Flash value works when using a tuple instead of an integer:

pyxif.ExifIFD.Flash: (1,), # Short

I couldn't get any Byte value to work, such as:

pyxif.GPSIFD.GPSAltitudeRef: 1

Both works well with EXIF, your pure PIL helper.

**Comment by hMatoba** [comment]
>E.g. assigning a Flash value works when using a tuple instead of an integer:

Tuple was implemented for any length value. Sometimes BYTE, SHORT, and LONG take two or more length value.
I'm thinking that the value should be checked length or not.

>couldn't get any Byte value to work

Fixed now,


Thank you.

**Comment by hMatoba** [comment]
Comments and suggestions are welcome : )

**Comment by SimonSteinberger** [comment]
I think tuples are fine, but it would be helpful for others if it were mentioned in the example code.

Anyways, as of this morning, we already are using your other app, "EXIF", in production on Pixabay. And it works really well so far! We've replaced the outdated app "pyexiv2" with EXIF in combination with Pillow.

If you can, write some more examples and/or a short documentation. Post it on Stackoverflow as an answer to relevant questions. There are people out there looking exactly for what you've created here. And it was really hard to find :-P

We'll keep on testing it on Pixabay ...

**Comment by hMatoba** [comment]
It's my pleasure that my code is used by Pixabay useful, cool and famous global web service.

I wrote "EXIF" to resolve an issue in Pillow. I don't know that I will keep developing "EXIF".
At least, I think I'll keep developing "Pyxif", so I recommend to use "Pyxif".

**Comment by hMatoba** [comment]
I made a documentation and wrote tuple matter there. I'll close this issue.
Ver. 1.0.0 document: http://piexif.readthedocs.org/en/1.0.x/appendices.html#exif-data-in-piexif

**Comment by SimonSteinberger** [comment]
It's a great start! If I find the time some day in the future, I'd definitely like to help you with this project.
