### ISSUE TITLE
module 'piexif' has no attribute 'load'

### ISSUE THREAD

**Issue by bu-ra3y** [hMatoba/Piexif#35]
Thank you for your work!

Hitting this issue:
```
import piexif
im='abc.tiff'
exif_dict = piexif.load(im)
```

which produces this error:

> AttributeError: module 'piexif' has no attribute 'load'

I tried this on Python: 
- 3.5.2
- 3.6.0
- 3.6.1

**Comment by hMatoba** [comment]
How did you install?

![1704280827370](https://cloud.githubusercontent.com/assets/4497270/25508383/9e208600-2bec-11e7-9720-75cbe417c965.jpg)

**Comment by bu-ra3y** [comment]
I found my problem: 
I was running my test of piexif from a script called piexif.py and the name of my script got in the way of the module name. 
Thank you for helping me figure it out.  I look forward to using piexif.
