### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by shibumi** [hMatoba/Piexif#38]
Hello,
Do you have any idea why the checks are failing?
https://paste.archlinux.de/B7l68f/

**Comment by hMatoba** [comment]
It would be error of PIL or Pillow.
In my test environment, using Pillow 4.0.0.

**Comment by shibumi** [comment]
We have pillow version 4.2.1 here on arch linux

**Comment by hMatoba** [comment]
I tried with pillow 4.2.1, and got same error as above.
With 4.0.0, no error occured.
For piexif test, use pillow 4.0.0.

**Comment by hMatoba** [comment]
I'll check how to avoid this error with latest pillow.

**Comment by shibumi** [comment]
@hMatoba thanks!

**Comment by hMatoba** [comment]
The problem has been solved in my environment.
Could you try the latest commit of piexif?
