### ISSUE TITLE
No Exif.Photo read and write capability

### ISSUE THREAD

**Issue by roth-a** [hMatoba/Piexif#39]
It seems piexif does not support Exif.Photo tags like 37510 Exif.Photo.UserComment (see http://www.exiv2.org/tags.html)

the field Exif.Photo.UserComment is correctly written (can be read by gwenview) by 
jhead -cl "test comment" file.jpg
However then Exif.Photo.UserComment is not read with
    exif_dict = piexif.load(filename)
    print(exif_dict)

Also writing it, does not mofiy the original "test comment"

**Comment by hMatoba** [comment]
Could you give me the "file.jpg"?

**Comment by roth-a** [comment]
https://github.com/roth-a/FaceTag/blob/master/demo/Barack_Obama_addresses_joint_session_of_Congress_2009-02-24.jpg

But it is not file specific. I also failed writing a gwenview/jhead compatible USercomment in other jpeg files.

**Comment by hMatoba** [comment]
Does this file have "37510" field?

**Comment by roth-a** [comment]
No it does not. But with jhead -cl you can write one.

**Comment by roth-a** [comment]
Is the problem reproducible on your system?

**Comment by hMatoba** [comment]
For "UserComment", piexif's is Incomplete implementation. It needs to follow the specification. But I don't have time to fix it soon.

**Comment by roth-a** [comment]
OK. Thanks for all you effort.

**Comment by hMatoba** [comment]
Thank you for informing here this matter : )

**Comment by mcoms** [comment]
I have a similar issue when trying to write `MakerNote` and `UserComment` on a file which doesn't have those. Maybe it's related?

```python
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> import piexif
>>> im = Image.open('1.jpg')
>>> exif_dict = piexif.load(im.info["exif"])
>>> piexif.dump(exif_dict)
b'Exif\x00\x00MM\x00*\x00\x00\x00 ... '
>>> exif_dict["0th"][piexif.ExifIFD.UserComment] = 'Testing'
>>> piexif.dump(exif_dict)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/piexif/_dump.py", line 63, in dump
    zeroth_set = _dict_to_bytes(zeroth_ifd, "0th", 0)
  File "/usr/local/lib/python3.4/dist-packages/piexif/_dump.py", line 293, in _dict_to_bytes
    value_type = TAGS[ifd][key]["type"]
KeyError: 37510
```

**Comment by hMatoba** [comment]
@roth-a 
I want a jpeg that has "UserComment".
I'll try it and resolve in next month.

**Comment by hMatoba** [comment]
![uc2](https://user-images.githubusercontent.com/4497270/30002599-33d7234c-90e8-11e7-890d-b64be3116f6c.jpg)

Ran `jhead -cl "test comment" file.jpg` and got above jpeg. I chekced UserComment field by both "http://exif.regex.info/exif.cgi" and "pillow". I couldn't get "UserComment" value. So, to run `jhead -cl "test comment" file.jpg` is not a correct way to insert "UserComment".

On the other hand, I found that it needs special way to read and write "UserComment". I'll implement helper function to read and write "UserComment" field.

**Comment by roth-a** [comment]
gwenview can read the comment written by jhead correctly.

**Comment by hMatoba** [comment]
"Exiftool(http://exif.regex.info/exif.cgi)", pillow, and piexif can't read. gwenview can read.

**Comment by hMatoba** [comment]
![uc2](https://user-images.githubusercontent.com/4497270/30002771-7f2f7ad4-90ec-11e7-9238-2279244ca8b9.jpg)

Inserted "UserComment" by exittool.
