### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by hMatoba** [hMatoba/Piexif#4]
"Pyxif" is not good name for exif library, because it lacks "exif" in name.
I think I might rename it "Piexif" or any name for SEO. "Pyexif" has already been on PyPI.

import piexif  # import pyxif

**Comment by SimonSteinberger** [comment]
Personally, I wouldn't mind either way. If you choose to rename it, no problem. The name "pyxif" and its intention were clear to me when I stumbled upon it.

**Comment by hMatoba** [comment]
Thank you. I'll rename this project in a few days.
