### ISSUE TITLE
What are the supported formats?

### ISSUE THREAD

**Issue by giumas** [hMatoba/Piexif#48]
By looking at the docs (http://piexif.readthedocs.io/en/latest/functions.html#load), they should be JPEG, WebP, and TIFF. 

If TIFF is fully supported, do you have an example of how to write EXIF tags of a file with this format?

What about PNG format? If not already supported, do you have plans to add it to this great small library?

**Comment by hMatoba** [comment]
TIFF: Not support to write
PNG: PNG doesn't support Exif.

**Comment by giumas** [comment]
I thought that Exif support was recently added to PNG format: https://stackoverflow.com/a/46595665/2741329

Any plan to add writing support for TIFF?

**Comment by hMatoba** [comment]
Thank you for telling me.

There is no plan to add wrting for TIFF.

**Comment by giumas** [comment]
Thank you for the quick feedback! 

About the no plan for TIFF writing is because of the required coding time? Or lack of interest from your side?

**Comment by hMatoba** [comment]
TIFF's header isn't called 'Exif'. It is called '(TIFF|File|Image) header'. So i think it isn't exif, but it looks like exif.
This library is for exif. I would drop support for TIFF.

**Comment by hMatoba** [comment]
For PNG.
https://github.com/hMatoba/Piexif/issues/49

**Comment by giumas** [comment]
I found this for [TIFF](https://www.loc.gov/preservation/digital/formats/fdd/fdd000145.shtml).

**Comment by hMatoba** [comment]
It is called 'Image File Header' in official specification. There is no 'Exif' in this document.
https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf

http://www.alternatiff.com/resources/TIFFPM6.pdf
