### ISSUE TITLE
load failing

### ISSUE THREAD

**Issue by jernejaMislej** [hMatoba/Piexif#50]
**About**

Load fails with some images, in some cases ValueError is thrown, but in some it will try to unpack and fail there.

**Notes**
EXIF can not be loaded, ValueError is not always thrown. Command line tools like `ExifTool` can read these files, but also have problems editing/writing back.
[pexif](https://pypi.python.org/pypi/pexif) can read and write
There seems to be an issue with the first tag (`InteropIndex`). Could this tag be skipped in such cases?
FYI, most common make and model we experience this issues:
```
SONY	 HDR-AS300
SONY	 HDR-AS200V
Garmin	 VIRBX
Garmin	 VIRBXE
```

**Data**
![0hqfncihmssmmhqgzqanpq](https://user-images.githubusercontent.com/19649323/35147931-bfb971aa-fd10-11e7-9617-0f6b664e38f0.jpg)
![0tx1netbeqatazdn588kta](https://user-images.githubusercontent.com/19649323/35147940-c42c980c-fd10-11e7-8472-6ce7c0f6f0c4.jpg)
![1nxubaunj5-z8eqkik4e5q](https://user-images.githubusercontent.com/19649323/35147941-c603b732-fd10-11e7-940f-ea0bf9458d1c.jpg)
![1vzo1xk8xf8nzmg7uwgjtg](https://user-images.githubusercontent.com/19649323/35147943-c72f1764-fd10-11e7-845f-7e1633cbd2e1.jpg)
![2xgoqkiztq7ww-fowy85sq](https://user-images.githubusercontent.com/19649323/35147947-c883b2aa-fd10-11e7-92cd-524e5ccfc4dc.jpg)
![3deweymbpzhjvqqik--ulw](https://user-images.githubusercontent.com/19649323/35147949-c9cea250-fd10-11e7-82a5-738ef0c770fb.jpg)
![3iq7cnod2ln2h7dvw78etg](https://user-images.githubusercontent.com/19649323/35147951-cb526ac6-fd10-11e7-9f29-8076624d3fc9.jpg)
![4necgkt2drys0di82lez3w](https://user-images.githubusercontent.com/19649323/35147956-cc849c0c-fd10-11e7-8066-449844d9fcae.jpg)
![7k42oeosvv-ksb7t5ahqta](https://user-images.githubusercontent.com/19649323/35147959-cd956054-fd10-11e7-8bf9-05a09ea4ea81.jpg)
![7shuhfkreihwztjfd4y7yg](https://user-images.githubusercontent.com/19649323/35147961-ce981910-fd10-11e7-86a6-56467de7e61e.jpg)
![8xd7n82jz8lw8lsduoaavg](https://user-images.githubusercontent.com/19649323/35147963-d0077b6a-fd10-11e7-9892-a8dd907d53e9.jpg)
![9bcjc7ma8knhhq8ra35gxg](https://user-images.githubusercontent.com/19649323/35147966-d10dbd94-fd10-11e7-88e9-bb416dc0a30b.jpg)
![9dnztz3bsuxqf5mnpwjwoa](https://user-images.githubusercontent.com/19649323/35147971-d1d62c0c-fd10-11e7-87f9-87dfbcd1e359.jpg)
![9l4v9tqjek5xtcesdji7uq](https://user-images.githubusercontent.com/19649323/35147973-d2d9e184-fd10-11e7-99de-df7052f8a858.jpg)
![17wfgoygkwlvlory9kyiyw](https://user-images.githubusercontent.com/19649323/35147974-d4097402-fd10-11e7-890f-2e979d4f7478.jpg)
![35u4dqsw6z-jqpim8wiysg](https://user-images.githubusercontent.com/19649323/35147975-d506906a-fd10-11e7-9543-009f388f34a2.jpg)
![96taipdqt27avd3d-dbfmw](https://user-images.githubusercontent.com/19649323/35147977-d6097f40-fd10-11e7-85b1-e04153234e38.jpg)
![adk64r3waaqsipou22mzva](https://user-images.githubusercontent.com/19649323/35147978-d707b9a2-fd10-11e7-925f-94203eac33ca.jpg)
![adwkxpub0461dpt2nfmoaw](https://user-images.githubusercontent.com/19649323/35147981-d8091026-fd10-11e7-8b52-f6903d1f5ade.jpg)
![ae2-mloiizpk8agkw6i5-g](https://user-images.githubusercontent.com/19649323/35147983-d9306e86-fd10-11e7-9b52-ee1ef50262cd.jpg)
![aeqb6vstcl0vxlnojzh0uw](https://user-images.githubusercontent.com/19649323/35147986-daf4866c-fd10-11e7-8377-ba778772015b.jpg)
![altmrsp5dfn1-u-2jqw5cg](https://user-images.githubusercontent.com/19649323/35147987-dbdf48be-fd10-11e7-8fc0-3b454d3bc0df.jpg)
![bii7prnxkdykb2xoqxyb6q](https://user-images.githubusercontent.com/19649323/35147988-dcdae2d2-fd10-11e7-9924-c5f8a132e9f5.jpg)
![bnbmt-d5tchp9opw0se4iq](https://user-images.githubusercontent.com/19649323/35147991-dddc4f22-fd10-11e7-9322-648d61fc0dd9.jpg)
![cqaesa5m4ngdvnqdg0bwow](https://user-images.githubusercontent.com/19649323/35147993-defdf716-fd10-11e7-960a-1f5c2bca3ece.jpg)

**Comment by hMatoba** [comment]
If I add some code to load broken files, Piexif get broken sometime soon. I think that a file doesn't have correct exif that isn't Piexif's matter.
Of course, if Piexif's has bug, I fix it.
