### ISSUE TITLE
Not writing in 1st

### ISSUE THREAD

**Issue by TiboDevC** [hMatoba/Piexif#53]
I think there is a mistake or a wrong behavior when adding information in the "1st" section.

In this example [(web site documentation)](http://piexif.readthedocs.io/en/latest/functions.html#dump), **no information are adding in section "ImageIFD"**.

Moreover, to be able to add information in this section, we need to also add a "thumbnail":
line 55 in _dump.py
`if (("1st" in exif_dict) and
            ("thumbnail" in exif_dict) and
            (exif_dict["thumbnail"] is not None)):`

If not thumbnail is adding in exif  information, the function `piexif.dump(exif_dict)` will ignore every thing contain in "1st". I did not read something about this restriction in the documentation.

Is it possible to fix it?

**Comment by hMatoba** [comment]
1st IFD is thumbnail's information. What do you use 1st IFD for?

**Comment by TiboDevC** [comment]
Oh, I thought it was also used to save Exif.Image.ImageDescription (0x010e).
