### ISSUE TITLE
TypeError: can only concatenate tuple (not "str") to tuple

### ISSUE THREAD

**Issue by donky84** [hMatoba/Piexif#6]
Congratulation, I really like your lib and I think it is very useful.
I am having some problems going through your example.
In specific when I execute the exif_bytes = piexif.dump(exif_dict)
I get the following error:
TypeError: can only concatenate tuple (not "str") to tuple

Let me know if it could be useful to get also the image file.
Thank you.

**Comment by hMatoba** [comment]
Thank you for informing me.
I want to get more detail.
Could you tell me specific value of "exif_dict"?

**Comment by donky84** [comment]
I am trying to do the piexif.dump(exif_dict)
on this picture.

Thanks for the quick response.

Have a wonderful day.

On Tue, Aug 18, 2015 at 8:33 PM, hMatoba <notifications@github.com> wrote:

> Thank you for informing me.
> I want to get more detail.
> Could you tell me specific value of "exif_dict"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hMatoba/Piexif/issues/6#issuecomment-132434241>.
>



-- 

*Davide Plud*

**Comment by hMatoba** [comment]
No picture is here : (

**Comment by donky84** [comment]
sorry:
https://d1haew79obdw6u.cloudfront.net/media/photos/full/2015/08/20/448839_262820_1440028988708.jpg

**Comment by hMatoba** [comment]
I checked the picture. The conclusion is that picture's exif data is wrong.
"Scene Type(in exif ifd, tag number is 41729)" value should be UNDEFINED type. It is written in exif official document(http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf). But the picture's "Scene Type" value is saved as SHORT. 
This library's "load" function just reads binary to get exif. On the other hand, "dump" function converts each value with reference to appropritate type. If exif values are saved as wrong type, they should be corrected before using "dump" function.
