### ISSUE TITLE
Dump writes the EXIF header only with byte align MM (\x4d\x4d) but for my implementation II (\x49\x49) would be needed

### ISSUE THREAD

**Issue by paniego** [hMatoba/Piexif#61]
As seen in the exif file format description (https://www.media.mit.edu/pia/Research/deepview/exif.html) , byte align can be type II or MM.

For the implementation i am using, load function is working with type II exif headers, but when i try to insert this kind of headers in another image, for what i need to dump the exif dictionary into bytes, this will be written with MM type

**Comment by hMatoba** [comment]
I won't support to write as "II".
