### ISSUE TITLE
Read `UserComment` when opened with Pillow

### ISSUE THREAD

**Issue by faroit** [hMatoba/Piexif#62]
I save UserComment data with piexif using the UserComment helper and dump it as exif bytes and write to jpg using pillow.

When I load the jpg with pillow, what is the best way to extract the UserComment using piexif without opening the file again (because its already opened with pillow)?

For now I came up with the following:

```Python
img = Image.open(buf)
exif_data = img._getexif()
piexif.helper.UserComment.load(exif_data[piexif.ExifIFD.UserComment])
```
is that how it is intended to work?

**Comment by hMatoba** [comment]
Use piexif's dict.

    exif_data = piexif.load(img.info["exif"])

http://piexif.readthedocs.io/en/latest/sample.html#with-pil-pillow

**Comment by faroit** [comment]
alright, thanks
