### ISSUE TITLE
Problem with unicode text in exif

### ISSUE THREAD

**Issue by hyanwong** [hMatoba/Piexif#8]
Using python 3, where strings are unicode by default, unicode characters are not properly embedded in EXIF data when using piexif.dump:

``` python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import urllib.request
from subprocess import call
import piexif

#NB adding e.g. chinese such as 仁 causes a 'ValueError: "dump" got wrong type of exif value.'
unicode_string = 'Some accented characters éé' 

test_jpg = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Felis_silvestris_silvestris.jpg/208px-Felis_silvestris_silvestris.jpg"
urllib.request.urlretrieve(test_jpg, "test1.jpg")
urllib.request.urlretrieve(test_jpg, "test2.jpg")

#try piexif unicode
piexif.insert(piexif.dump({"0th":{piexif.ImageIFD.Copyright:unicode_string}, "Exif":{}}), "test1.jpg")
#try exiftool unicode
call(['exiftool', u'-copyright='+unicode_string, "test2.jpg"])

#print result
call(['exiftool', '-copyright', "test2.jpg", "test1.jpg"])
```

**Comment by hMatoba** [comment]
Example is here.

    s = u"XXXXXXX"
    exif_bytes = piexif.dump({"0th":{piexif.ImageIFD.Make:s.encode("utf8")}})
    new_jpg = piexif.insert(exif_bytes, jpg)
    
    exif_dict = piexif.load(new_jpg)
    maker = exif_dict["0th"][piexif.ImageIFD.Make].decode("utf8")
    print(maker)

**Comment by hyanwong** [comment]
Great, that works in python3 too (i.e. if I call unicode_string.encode("utf8") in the exif array). Could this be documented?
