### ISSUE TITLE
ValueError: Exif might be wrong. Got incorrect value type to decode.

### ISSUE THREAD

**Issue by GustavePate** [hMatoba/Piexif#9]
Hi there,

Got this error with my photos taken with my DMC-FT5 Panasonic Camera.

    ValueError: Exif might be wrong. Got incorrect value type to decode.
    tag: 40962
    type: 9

Which links to the [comment here in your code](https://github.com/hMatoba/Piexif/blob/877ded36bcec7f840d72bd84f24b883733ab9f3f/piexif/_load.py#L182)

Attached is a sample code and photo to replay the bug.

Thanks for your lib which is very handy I intend to use it for my project [lycheesync](https://github.com/GustavePate/lycheesync/tree/py3unittest) but if it can't recognize my own photos It will be a no go. I hope you can fix it, but I think the code is not commented for no reason.

Good luck with this one and thanks again for your lib !

[attachement.zip](https://github.com/hMatoba/Piexif/files/99971/test.zip)

**Comment by hMatoba** [comment]
In haste, why error occurred.

It looks the value type is saved as SLONG. Correct type of tag "40962(Exif IFD)" should be SHORT or LONG.
 - http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf

 I'll think how to avoid it on this weekend.

**Comment by hMatoba** [comment]
Why SLONG is commented out is no value uses SLONG as it's type in exif document.
http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf

Clear the comment marks and run the code : )

**Comment by GustavePate** [comment]
Hi, thanks for your quick reply !

Obviously Panasonic is not very good at reading the specs ;)

I could clear comments and run the code for my own use (no doubt it will work) but obviously users of my project will just:

     pip install piexif

As I said if it crash for all Panasonic camera users, it will be a no go.
For backward compatibility, SLONG is supported by other tools like imagemagic. 

Is your answer a way to tell me that you won't support SLONG in your lib ?

**Comment by hMatoba** [comment]
pip install... I got it.
I'll fix it and upload a new version on PyPI in a few days.

**Comment by GustavePate** [comment]
Thank you !

**Comment by hMatoba** [comment]
Done : )

**Comment by GustavePate** [comment]
Wonderfull ! Thanks a lot ! Now I can release my script next version ;)
